function specs = opa657()
%#Opamp is OPA657
%http://www.ti.com/lit/ds/symlink/opa657.pdf
OPAMP_GBP = 1.6E9 %1.6 Ghz
OPAMP_OPENLOOPGAIN = 3100 %70db
OPAMP_VNOISE_PEAK = 30E-9 %30nV/root(Hz)
OPAMP_VNOISE_FREQ = 1.1E3
OPAMP_VNOISE_TROUGH = 4.8E-9 %4.8nV/root(Hz)
OPAMP_VNOISE = opamp_vnoise(OPAMP_VNOISE_PEAK, OPAMP_VNOISE_FREQ, OPAMP_VNOISE_TROUGH, w);
OPAMP_INOISE = 1.3E-15

specs = [OPAMP_3DB_OPENLOOP, OPAMP_DC_GAIN, OPAMP_VNOISE, OPAMP_INOISE];
end
